apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme.v02.api.letsencrypt.org/directory
    email: "quikstudio2021@gmail.com"
    privateKeySecretRef:
      # letsencrypt during verification, will send a dummy key back to us, not sure what it is used for
      name: letsencrypt-prod
    solvers:
      - http01:
        ingress:
          class: nginx
